# -*- coding: utf-8 -*-
"""Team-project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AA0s29QrMNbVikMSy-Ytwop-rFIHbMLI
"""

!pip install beautifulsoup4
!pip install requests

chart_f = open("./recent_chart.txt","w")

import requests as rq
from bs4 import BeautifulSoup as bs

req = rq.get('https://movie.naver.com/movie/sdb/rank/rmovie.naver')

html = req.text
soup = bs(html,'html.parser')

words=soup.findAll('div',{'class':'tit3'})

from datetime import datetime as dt
time = dt.now()

print('{}'.format(time))
print('NAVER 영화 실시간 랭킹')
for i in range(20):
  print('{0:2d}위:{1}'.format(i+1,words[i].text))

chart_f.close()